-- MySQL Script generated by MySQL Workbench
-- Mon Jan 20 09:53:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_companies
-- -----------------------------------------------------
USE companies;
-- -----------------------------------------------------
-- Table `companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `companies` ;

CREATE TABLE IF NOT EXISTS `materiales` (
  `id_material` INT NOT NULL AUTO_INCREMENT,
  `nombre_material` VARCHAR(1000) NOT NULL,
  `simbolo_material` VARCHAR(1000) NULL,
  `categoria_material` VARCHAR(1000) NULL,
  `descripcion_material` VARCHAR(1000) NULL,
  PRIMARY KEY (`id_material`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `aleaciones` (
  `id_aleaciones` INT NOT NULL AUTO_INCREMENT,
  `nombre_aleacion` VARCHAR(1000) NOT NULL,
  `simbolo_aleacion` VARCHAR(1000) NOT NULL,
  `descripcion_aleacion` VARCHAR(10000) NULL,
  PRIMARY KEY (`id_aleaciones`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `dispositivo` (
  `id_dispositivo` INT NOT NULL AUTO_INCREMENT,
  `nombre_dispositivo` VARCHAR(1000) NOT NULL,
  `descripcion_dispositivo` VARCHAR(1000) NULL,
  `imagen_dispositivo` VARCHAR(1000) NULL,
  PRIMARY KEY (`id_dispositivo`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

--POBLADO DE DATOS MATERIALES
INSERT INTO materiales(id_material, nombre_material, simbolo_material, categoria_material, descripcion_material) VALUES(856,'Titanio','Ti','Metal','El titanio es un material biomédico');


-- POBLADO DE DATOS DISPOSITIVO
INSERT INTO dispositivo(id_dispositivo, nombre_dispositivo, descripcion_dispositivo, imagen_dispositivo) VALUES(48,'Implante de cadera','Los impiones de titanio, conte','imagen de cadera');


--POBLADO DE DATOS ALEACIONES
INSERT INTO aleaciones(id_aleaciones,nombre_aleacion, simbolo_aleacion, descripcion_aleacion) VALUES(35,'Titanio-Aluminio-Vanadio','Ti-6Al-4V','Esta aleación de tirticulaciones dañadas');
